# Notification Service Configuration (Docker/Production overrides)

spring:
  data:
    mongodb:
      uri: mongodb://mongodb:27017/notificationdb
    redis:
      host: redis
  rabbitmq:
    host: rabbitmq
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME:vnhat.dev@gmail.com}
    password: ${MAIL_PASSWORD:okfq hhgf juor jqxy}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

eureka:
  client:
    service-url:
      defaultZone: http://discovery-server:8761/eureka/
