# Payment Service Configuration (Docker/Production overrides)
# This file is served by Config Server and overrides application.yml defaults

spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/paymentdb
    username: sa
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
  rabbitmq:
    host: rabbitmq



eureka:
  client:
    service-url:
      defaultZone: http://discovery-server:8761/eureka/

